grem11n/terraform-aws-vpc-peering

README.md
main.tf
outputs.tf
variables.tf

Issue #2. fix typo

---

CHANGELOG.md
README.md
data.tf
examples/simple-peering/README.md
examples/simple-peering/main.tf
examples/simple-peering/outputs.tf
main.tf
outputs.tf
variables.tf

I guess final refactoring for Terraform 0.11

Refactoring for Terraform 0.11

---

README.md
data.tf
main.tf
outputs.tf
variables.tf

Also, I remove:
``` 
peer_region
cross_region_peering
create_peering
```
variables and made the code more simple.

terraform 0.12 support

---

main.tf

as par:
https://github.com/grem11n/terraform-aws-vpc-peering/commit/eff16500c4541807440e7aa28d6922824e12ff20

fix route list count for terraform v0.11

---

CHANGELOG.md
data.tf
examples/single-account-multi-region/README.md
examples/single-account-multi-region/main.tf
examples/single-account-multi-region/outputs.tf
examples/single-account-multi-region/provider.tf
examples/single-account-multi-region/variables.tf
examples/single-account-single-region-with-options/README.md
examples/single-account-single-region/README.md
main.tf
outputs.tf
test/fixtures/single-account-multi-region/main.tf
test/fixtures/single-account-multi-region/outputs.tf
test/fixtures/single-account-multi-region/provider.tf
test/fixtures/single-account-multi-region/variables.tf
test/peering-active_test.go

* Added test for cross-region peering in the same AWS account
* Fixed cross-region peering for TF < 0.12 version

Single account multi region peering

---

CHANGELOG.md
examples/multi-account-multi-region/README.md
examples/multi-account-multi-region/main.tf
examples/multi-account-multi-region/outputs.tf
examples/multi-account-multi-region/provider.tf
examples/multi-account-multi-region/variables.tf
main.tf
outputs.tf
test/fixtures/multi-account-multi-region/main.tf
test/fixtures/multi-account-multi-region/outputs.tf
test/fixtures/multi-account-multi-region/provider.tf
test/fixtures/multi-account-multi-region/variables.tf
test/peering-active_test.go

* Tests for cross-account / cross-region peering configuration
* Mark variable `peer_account_id` for deprecation

Tests for multi-region

---

main.tf

TF 0.11 version fix equivalent to #35 - note this also (I think) fixes the default peer_region calculation.

Tags the same if overlapping resources

---

.github/workflows/terratest.yml
examples/multi-account-multi-region/main.tf
examples/single-account-single-region-with-options/README.md
examples/single-account-single-region-with-options/main.tf
examples/single-account-single-region/README.md
examples/single-account-single-region/main.tf
examples/single-account-single-region/variables.tf
test/fixtures/multi-account-multi-region/main.tf
test/fixtures/multi-account-multi-region/variables.tf
test/fixtures/single-account-multi-region/main.tf
test/fixtures/single-account-multi-region/variables.tf
test/fixtures/single-account-single-region-with-options/variables.tf
test/fixtures/single-account-single-region/variables.tf

* Update Terraform version anf Go version in CI
* Fixes https://github.com/grem11n/terraform-aws-vpc-peering/issues/48
* Fixes https://github.com/grem11n/terraform-aws-vpc-peering/issues/52

Update TF & Go version for CI

---

.github/workflows/terratest.yml

Upgrade Terraform version

---

.github/workflows/terratest.yml
CHANGELOG.md
README.md
examples/module-depends-on/README.md
examples/module-depends-on/main.tf
examples/multi-account-multi-region/README.md
examples/single-account-multi-region/README.md
examples/single-account-multi-region/provider.tf
examples/single-account-single-region-with-options/README.md
examples/single-account-single-region/README.md

Closes https://github.com/grem11n/terraform-aws-vpc-peering/issues/57

Docs for v3.0.0 release

---

.github/workflows/terratest.yml
main.tf

* Add execution timeouts for create/delete operations
* Test against `0.14.10` and `0.15.0` versions of Terraform

Execution timeouts

---

.github/workflows/terratest.yml
README.md
main.tf
provider.tf

* Removed [empty provider declarations](https://www.terraform.io/upgrade-guides/0-15.html#alternative-provider-configurations-within-modules) and switched to `configuration_aliases`
* Updated test version in GitHub Actions
* Added timeouts for create/delete operation

Upgrade to TF0.15

---

.github/workflows/terratest.yml

Use the [new updated GitHub Action](https://github.com/hashicorp/setup-terraform) for Terraform Fmt

Udate GH action version

---

.github/workflows/terratest.yml
examples/module-depends-on/provider.tf
examples/module-depends-on/variables.tf
examples/multi-account-multi-region/provider.tf
examples/single-account-multi-region/README.md
examples/single-account-multi-region/provider.tf
examples/single-account-single-region-with-options/README.md
examples/single-account-single-region-with-options/provider.tf
examples/single-account-single-region/README.md
examples/single-account-single-region/provider.tf
test/fixtures/multi-account-multi-region/provider.tf
test/fixtures/multi-account-multi-region/variables.tf
test/fixtures/single-account-multi-region/provider.tf
test/fixtures/single-account-multi-region/variables.tf
test/fixtures/single-account-single-region-with-options/provider.tf
test/fixtures/single-account-single-region-with-options/variables.tf
test/fixtures/single-account-single-region/provider.tf
test/fixtures/single-account-single-region/variables.tf
version.tf

* Pin version >= 0.15
* Change test regions to Europe

Pin version >=0.15

---

.github/workflows/terratest.yml

Use the latest TF for tests

---

examples/associated-cidrs/main.tf
examples/associated-cidrs/outputs.tf
examples/associated-cidrs/provider.tf
examples/associated-cidrs/variables.tf
locals.tf
main.tf
test/fixtures/associated-cidr/main.tf
test/fixtures/associated-cidr/outputs.tf
test/fixtures/associated-cidr/provider.tf
test/fixtures/associated-cidr/variables.tf
test/peering-active_test.go

Create fixtures for associated CIDR block for VPCs to create a test for this case.

Create fixtures for associated CIDRs

---

.github/workflows/terratest.yml

- Terraform `1.2.9` => `1.3.7`
- Go `1.18` => `1.19`

Update Terraform version in tests

---

README.md
examples/associated-cidrs/README.md
examples/module-depends-on/README.md
examples/multi-account-multi-region/README.md
examples/multi-account-single-region/README.md
examples/single-account-multi-region/README.md
examples/single-account-single-region-with-options/README.md
examples/single-account-single-region/README.md

- Fix some typos
- Update the docs according to the Markdown linter findings
- Remove broken links from the docs
- Add documentation for the `associated_cidrs` example

Update the docs

---

.gitignore
data.tf
examples/partial-subnets/main.tf
examples/partial-subnets/outputs.tf
examples/partial-subnets/provider.tf
examples/partial-subnets/variables.tf
locals.tf
test/fixtures/partial-subnets/data.tf
test/fixtures/partial-subnets/main.tf
test/fixtures/partial-subnets/outputs.tf
test/fixtures/partial-subnets/provider.tf
test/fixtures/partial-subnets/variables.tf
test/peering-active_test.go

Added test fixtures, example use case, fixing code. 
Did not ran tests for other examples.

This is a fix for #108

---

examples/module-depends-on/README.md

Hi @grem11n,
Please, accept and merge this pull request. This is my first PR in open source. Let me know if any changes to be done.
Thanks & Regards
Karim

Fix typo in examples/module-depends-on/README.md #104

---

.github/workflows/terratest.yml
examples/custom-name-tag/README.md
examples/custom-name-tag/main.tf
examples/custom-name-tag/outputs.tf
examples/custom-name-tag/provider.tf
examples/custom-name-tag/variables.tf
locals.tf
main.tf
test/peering-active_test.go

Fixes #111 
+ adds a test case for this issue

Fix broken name tag

---

.github/workflows/terratest.yml

- Update the Terraform version for tests
- Use `richgo` instead of a plain `go`

Update TF version for tests
